- name: docker build and push
  hosts: all
  become: yes

  vars:
    docker_username: "{{ lookup('env','DOCKER_USER') }}"
    docker_password: "{{ lookup('env','DOCKER_PASS') }}"

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Build Docker Image
      command: docker build -t 2048-game .
      args:
        chdir: /var/lib/jenkins/workspace/2048-Gaming-App-pipeline

    - name: Tag image
      command: docker tag 2048-game "{{ docker_username }}/2048-game:latest"

    - name: Log in to Docker Hub
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"

    - name: Push image
      command: docker push "{{ docker_username }}/2048-game:latest"

    - name: Run container
      command: docker run -d --name 2048-game -p 8081:80 "{{ docker_username }}/2048-game:latest"
